Update payment meta methods, storage
easydigitaldownloads/edd-campaign-tracker pull request #12
Opened 2021-06-03 20:45 UTC by robincornett

Fixes #11 

Proposed Changes:
1. Add an EDD 3.0 order meta function to store campaign information.
2. Update the campaign info rendering method to retrieve 3.0 order metadata and convert old metadata if it exists.
3. Add a migration function for sites updating to EDD 3.0 to automatically move payment meta to new order meta. (pending)

2021-06-15 17:59 UTC, LisaCee requested changes
Just the one comment for now. 

I'm guessing to test, I migrate a site with Campaign Tracker from 2.x > 3 and double check that the meta is correct...

2021-06-15 17:59 UTC, LisaCee commented on includes/campaign-logger.php
> +	 * @param int $order_id
Will you add a description for this param?

2021-06-15 18:37 UTC, robincornett commented
@LisaCee yes, if you migrate orders on a site with campaign tracker data (you can do this on a site where you've already run a migration and empty any `edd_` order related tables, then use CLI to run `wp edd migrate_payments --force` to run the order migration again anyway).

It should also work on an existing site running EDD 3.0 without going through the migration process, though, and you can test that first, before doing a migration, by viewing any order with campaign data attached to it (they should show in the payments list table). The data should be visible, but the extension/PR should silently migrate the old data to the new order metadata, and you can check that directly in the database.

2021-06-15 23:40 UTC, LisaCee approved these changes
- [x] 2.x migration to 3.0
- [x] 3.0 + release 1.0.2 correctly updated the meta when changed to 3.0 + this branch

2021-06-30 10:49 UTC, ashleyfae commented
## Tested

- [x] Nothing changes in EDD 2.10
    - [x] Create campaign data in master / EDD 2.10.
    - [x] Switch to this branch.
    - [x] Ensure nothing changes.
- [ ] Data preserved during 3.0 migration
    - [ ] Create campaign data in master / EDD 2.10
    - [ ] Switch to this branch.
    - [ ] Migrate to EDD 3.0
    - [ ] Ensure data is still there.
- [ ] Data preserved when updating Campaign Tracker after 3.0 migration.
    - [ ] Create campaign data in master / EDD 2.10
    - [ ] Migrate to EDD 3.0
    - [ ] Switch to this branch.
    - [ ] Ensure data is still there.

2021-06-30 12:26 UTC, ashleyfae approved these changes

2021-06-30 12:26 UTC, merged